---
- name: Heketi
  become: True
  block:
    - name: Download heketi-client from github
      get_url:
        url: 'https://github.com/heketi/heketi/releases/download/{{ heketi.version }}/heketi-client-{{ heketi.version }}.linux.{{ heketi.arch }}.tar.gz'
        dest: '/tmp/heketi-client-{{ heketi.version }}.linux.{{ heketi.arch }}.tar.gz'

    - name: Download heketi from github
      get_url:
        url: 'https://github.com/heketi/heketi/releases/download/{{ heketi.version }}/heketi-{{ heketi.version }}.linux.{{ heketi.arch }}.tar.gz'
        dest: '/tmp/heketi-{{ heketi.version }}.linux.{{ heketi.arch }}.tar.gz'

    - name: Create folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/heketi
        - /var/lib/heketi

    - name: Unarchive heketi
      unarchive:
        src: '/tmp/heketi-client-{{ heketi.version }}.linux.{{ heketi.arch }}.tar.gz'
        dest: /bin
        exclude:
          - heketi.json
        remote_src: yes

    - name: Configuring heketi toloplogy
      template:
        src: "{{ inventory_dir }}/../roles/heketi/files/topology-sample.j2"
        dest: "/usr/share/heketi/topology-sample.json"

    - name: Configuring heketi json
      template:
        src: "{{ inventory_dir }}/../roles/heketi/files/heketi.j2"
        dest: "/etc/heketi/heketi.json"

    - name: enable gluster
      ansible.builtin.systemd:
        name: glusterd
        state: started
        enabled: yes

